static_resources:
  listeners:
    - name: http
      address:
        socket_address:
          address: '::'
          port_value: 80
          ipv4_compat: true
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: 'router'
                http_filters:
                  - name: envoy.router
                    typed_config: {}
                route_config:
                  name: http
                  virtual_hosts:
                    - name: redirect
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          redirect:
                            https_redirect: true
    - name: https
      address:
        socket_address:
          address: '::'
          port_value: 443
          ipv4_compat: true
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: 'router'
                http_filters:
                  - name: envoy.router
                    typed_config: {}
                route_config:
                  name: https
                  virtual_hosts:
                    - name: xsuportal
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/xsuportal.proto.services.bench.BenchmarkQueue/"
                          route:
                            cluster: xsuportal_api
                        - match:
                            prefix: "/xsuportal.proto.services.bench.BenchmarkReport/"
                          route:
                            cluster: xsuportal_api
                        - match:
                            prefix: "/"
                          route:
                            cluster: xsuportal_web
                use_remote_address: true
                access_log:
                  - name: envoy.file_access_log
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /var/log/envoy/access.log
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext"
              common_tls_context:
                alpn_protocols: ["h2", "http/1.1"]
                tls_params:
                  tls_minimum_protocol_version: "TLSv1_2"
                  tls_maximum_protocol_version: "TLSv1_2"
                tls_certificates: 
                  - certificate_chain: {"filename": "/etc/ssl/private/tls-cert.pem"}
                    private_key: {"filename": "/etc/ssl/private/tls-key.pem"}
  clusters:
    - name: xsuportal_web
      type: STATIC
      connect_timeout: 0.25s
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: xsuportal_web
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "127.0.0.1"
                      port_value: 9292
    - name: xsuportal_api
      type: STATIC
      connect_timeout: 0.25s
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      load_assignment:
        cluster_name: xsuportal_api
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "127.0.0.1"
                      port_value: 50051
